title: "Davide Netti's Computer Science blog."
description: "Personal (simple) blog where i publish stuffs i'm working on."
baseurl: ""
url: "https://davidenetti.github.io"

markdown: kramdown
plugins:
  - jekyll-feed
